# Generated by Django 3.2.13 on 2022-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
