# Generated by Django 3.2.13 on 2022-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='location',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='company',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='skills',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='skills_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
